version: '3.9'

services:
  postgresdb:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    volumes:
      - /var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=3c0mm3rc3Pr0duct
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce_db
